### ISSUE TITLE
PA Review: Reviews/photos of hikes

### ISSUE THREAD

**Issue by benrose207** [benrose207/AllHikes#10]
Live link: http://all-hikes.herokuapp.com
To test hike pages: http://all-hikes.herokuapp.com/#/hikes/11 (seeds exist from hikeIds 11- 15)

- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

- [x] Users can leave reviews on individual hikes
- [x] Users can edit and delete reviews they have created
- [x] Users can upload photos for individual hikes
- [x] Users can view a dedicated profile page for their account, displaying their reviews and photos

**Comment by benrose207** [comment]
@linakherchi , I know we're wrapping up the FSP phase of the curriculum, so I wanted to send you this feature for review before we switch over to MERN stack. There are certainly some improvements and tweaks I'd like to make to portions of this at a later date, but I should have all the main functionality built and working as it stands now. This feature covers all CRUD actions for reviews, uploads for photos on hikes, as well as the ability to see both by user in their individual profiles.

Let me know your feedback!

**Comment by linakherchi** [comment]
Hi Ben ! 

I added all my comments on the FSP spreadsheet. These include this feature.
