### ISSUE TITLE
PA Review: Hikes

### ISSUE THREAD

**Issue by benrose207** [benrose207/AllHikes#9]
Live link: http://all-hikes.herokuapp.com
To test hike pages: http://all-hikes.herokuapp.com/#/hikes/1 (seeds exist from hikeIds 1 - 5)

- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

- [x] User can see detailed hike information on an individual hike page
- [x] Users can see a basic map of the trail
- [x] Users can click for driving directions to the trailhead

Note: the following features are intentionally _not_ included in this feature, as are/rely on other features yet to be built:
- Reviews
- Aggregate review data on hikes
- Nearby hikes (relies on Park data to get other hikes)
- Distinct cover photos for hikes - relies on Photos table built in next feature
- Search for different hikes

**Comment by benrose207** [comment]
@linakherchi , submitting this issue for code review of Feature #2! See notes in description above for how to test. Let me know if you have any questions whatsoever, or any ways in which this feature can be cleaned up/improved! 

In the meantime, I'll be moving on towards the basics of the Reviews feature, if that's okay with you.

**Comment by linakherchi** [comment]
Hi @benrose207 ! 

Thank you for submitting your new feature. 

It looks great but I have some comments that are mostly related to the way your components are presented.

1) Your footer has different positions depending on the page we are in, which may lead to have white space left in the bottom for some of these pages.

For example, when I click on 'sign up for free', I can see that space. Similar when I am in the Hike Show Page and then click on 'contact'.

2) Lots of gray area around the minified map on the Hike Show page.

3) When I am in the Hike Show Page with the map that presents the details of the route, there is a small button at the top left that says 'View Hike Details' and that sends me back to the Hike Show page. I think that this can be misleading as I have more details about the Hike when I am in the page that has the map with the route and not the other way around.

Other than that you have done a great job ! 

Regarding your questions about splitting a component into multiple sub-components, I think that's a great idea and would make it easier for you to understand if you try to modify it months for now, and would allow interviewers to understand faster.

Let me know if you have any questions.

**Comment by benrose207** [comment]
Hey Lina, thanks for this feedback! A few thoughts:

1. Any chance you could send a screenshot of this? I'm unable to reproduce myself on my laptop, but maybe it has to do with screen size if you have a larger monitor? In the meantime, I made a tweak that hopefully should take care of it.
2. For the gray area around the minified map -- do you mean below it or on the sides? My plan eventually is to add a list of "Nearby Hikes" below that map preview, which should fill up that column nicely and get rid of the blank space. I'm planning on doing that by just showing other hikes in the same park, so can't build that until I get my park feature built though. 
3. Went ahead and changed this to "Return to Hike Details" -- hopefully that's clearer but let me know if you have any other ideas!

I'll find some time to go back over my Hike Show page in particular and see if it can be decomposed at all into sub-components. Let me know if you have any advice for how to determine where a component can/should be broken out further!

Pushed those couple small changes to Heroku if you want to check them out. There's a bunch of other stuff up there now as well for reviews and photo uploads, but I'll hopefully be putting in a separate issue to review that feature tomorrow.

**Comment by linakherchi** [comment]
1. Thanks @benrose207 ! It is looking great now and there is no white space under your footer.
2. Ok ! I did not know that you had the intention to fill it later. 
3. Great!

New point that I just noticed is that when I click on Sign up for free and even though I sign up as a demo user, the sign up for free button does not disappear.

Looking at your Hike Show Component, the first subcomponent that I am seeing and that you can create is one starting at: 
- `<article className="hike-main-content">` - line 177
 and ending at 
-  ` <section>
            {hikeUserContent}
        </section>
     </article>` - line 216 

The reason that led me to chose this part is that all of these lines depend on only the hike prop. You can definitely create a subcomponent for it and pass in hike as a prop to be used inside that subcomponent.

Let me know if you want to discuss this further !

**Comment by benrose207** [comment]
Great idea about that subcomponent! I went ahead this morning and pulled most of that out into it's own new component, which definitely makes these files easier to read. 

I planned on replacing that Sign Up For Free button with a link to my search page once I built that feature, but I can certainly hide for now, since I haven't gotten around to that yet.
